### ISSUE TITLE
Revise syntax for improved compatibility with `dplyr`

### ISSUE THREAD

**Issue by mjwestgate** [AtlasOfLivingAustralia/galah#101]
We've recently received feedback that the use of `select_` prefix is confusing, because we use it for choosing both rows and columns, whereas it is more common (e.g. in `dplyr`, `SQL`) for `filter` to refer to rows and `select` to refer to columns. It's also inconsistent to use NSE in `select_filters` but not in other functions.

Proposed solution is to use `galah_` prefix, followed by a `dplyr` equivalent suffix, e.g.

- `galah_filter` for rows
- `galah_select` for columns
- `galah_group_by` to pass to `ala_counts`

**Comment by daxkellie** [comment]
After discussion, we have decided to change `select_locations` to `galah_geolocate`. This change is consistent with the `galah_` prefix solution because:
* the suffix is a verb (e.g., `filter`, `select`, `group_by`)
* This hopefully specifies more clearly that the function requires a specific input (e.g., a polygon or shape file) compared to `galah_filter`, which can also filter by broad locations like states/territories.
