### ISSUE TITLE
Cache `search_fields()` results within a session

### ISSUE THREAD

**Issue by matildastevenson** [AtlasOfLivingAustralia/galah#73]
Could use `memoise` to do this, or could cache in the same way as downloaded data, but this would preserve results between sessions.

**Comment by mjwestgate** [comment]
Follow-up: This is important because when `galah_config(run_checks = TRUE)` is set, every call to `select_filters` or `select_columns` (and a few others, like `ala_counts`) has to run `search_fields` first. This is _very_ slow for something that would otherwise simply return some parsed text.

Proposed solution is:

- add `valid_fields` slot to `galah_config` which is a length-zero vector by default (i.e. `c()`)
- consolidate `validate_fields()` and `validate_cols` into a single function (e.g. `validate_fields()`)
- on package load, leave `galah_config(valid_fields)` as empty
- on first call to `validate_fields`, update `valid_fields`
- prevent `galah_config` from saving/loading information from `valid_fields` to profile (i.e. no long-term storage)

This should work within a session without slowing package loading, while also preventing long-term storage
